### ISSUE TITLE
your site redirect to porn site

### ISSUE THREAD

**Issue by BIGITIMI** [KingYes/jquery-radio-image-select#7]
Hi yakir
the link to your personal site is linked to a porn site i think
please check it out

**Comment by KingYes** [comment]
Hi @BIGITIMI 
I don't use this domain anymore.. So I don't know who buy this later..

**Comment by BIGITIMI** [comment]
so i suggest you to remove the link...

**Comment by KingYes** [comment]
Thank you :)
